name: Deploy Application

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Run Deploy Script
        run: |
          BRANCH=${{ github.ref_name }}
          echo "🌿 Branch detectada: $BRANCH"

          if [ "$BRANCH" == "main" ]; then
            ENVIRONMENT="prod"
            PM2_NAME="portal-admin-prod"
          elif [ "$BRANCH" == "staging" ]; then
            ENVIRONMENT="staging"
            PM2_NAME="portal-admin-staging"
          else
            echo "❌ Branch $BRANCH não configurada para deploy."
            exit 1
          fi

                    ssh -o StrictHostKeyChecking=no ubuntu@18.207.6.216 << EOF
            export NVM_DIR="/home/ubuntu/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            export PATH="\$PATH:/home/ubuntu/.nvm/versions/node/$(node -v)/bin"
            export ENVIRONMENT=$ENVIRONMENT
            export BRANCH=$BRANCH
            export PM2_NAME=$PM2_NAME

            echo "🔍 Ambiente detectado: \$ENVIRONMENT"
            if [ ! -d "/home/ubuntu/Projetos/portal-admin-\$ENVIRONMENT" ]; then
              echo "❌ Diretório /home/ubuntu/Projetos/portal-admin-\$ENVIRONMENT não encontrado."
              exit 1
            fi

            cd /home/ubuntu/Projetos/portal-admin-\$ENVIRONMENT

            echo "⌛⏳ REALIZANDO PULL ... ⌛⏳"
            git checkout \$BRANCH
            git pull

            echo "⌛⏳ INSTALANDO AS DEPENDÊNCIAS ... ⌛⏳"
            yarn || { echo "❌ Erro ao instalar dependências."; exit 1; }

            echo "⌛⏳ COMPILANDO APLICAÇÃO... ⌛⏳"
            yarn build || { echo "❌ Erro ao compilar a aplicação."; exit 1; }

            echo "🚀 REINICIANDO APLICAÇÃO COM PM2 🚀"
            pm2 restart \$PM2_NAME || { echo "❌ Erro ao reiniciar aplicação no PM2."; exit 1; }
            pm2 save || { echo "❌ Erro ao salvar estado do PM2."; exit 1; }

            echo "✅✅✅ DEPLOY FINALIZADO PARA O AMBIENTE \$ENVIRONMENT ✅✅✅"
          EOF
